Script started on 2015年03月11日 (週三) 00時38分30秒
]0;F74031108@2015cpp: ~F74031108@2015cpp:~$ whoami; pwd
F74031108
/home/F74031108
]0;F74031108@2015cpp: ~F74031108@2015cpp:~$ git config ‐l
error: key does not contain a section: ‐l
]0;F74031108@2015cpp: ~F74031108@2015cpp:~$ git config --global user.email "you@example.com"[1P"[1P"[1P"[1P"[1P"[1P"[1P"[1P"[1P"[1P"[1P"[1P"[1P"[1P"[1P"c"l"o"u"d"s"t"r"i"f"e"6"0"1"3"8"@"g"m"a"i"l"."c"o"m" [A]0;F74031108@2015cpp: ~F74031108@2015cpp:~$ [C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C

]0;F74031108@2015cpp: ~F74031108@2015cpp:~$ git config --global user.name "Your Name"[1P"[1P"[1P"[1P"[1P"[1P"[1P"[1P"[1P"s"s"1"2"f"3"2"v"
]0;F74031108@2015cpp: ~F74031108@2015cpp:~$ git config --global color.ui true
]0;F74031108@2015cpp: ~F74031108@2015cpp:~$ git config --global core.editor vim
]0;F74031108@2015cpp: ~F74031108@2015cpp:~$ git config --global alias.co commit
]0;F74031108@2015cpp: ~F74031108@2015cpp:~$ git config --global alias.lg "log --color --graph --all --p retty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)< %an>%Creset' --abbrev-commit --"
]0;F74031108@2015cpp: ~F74031108@2015cpp:~$ git config ‐l
error: key does not contain a section: ‐l
]0;F74031108@2015cpp: ~F74031108@2015cpp:~$ git clone https://github.com/<your github account>/lab1.git [A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[1P/lab1.git
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.gitd/lab1.gitd/lab1.git[1P/lab1.git[1P/lab1.gits/lab1.gits/lab1.git1/lab1.git2/lab1.gitf/lab1.git3/lab1.git2/lab1.gitv/lab1.git
fatal: destination path 'lab1' already exists and is not an empty directory.
]0;F74031108@2015cpp: ~F74031108@2015cpp:~$ ls
[0m[01;34mlab1[0m  lab1.script
]0;F74031108@2015cpp: ~F74031108@2015cpp:~$ exit

Script done on 2015年03月11日 (週三) 00時41分53秒
